/**
 * 预设提示词模板库
 * 包含20个精选模板: 电影(5) / 广告(5) / 社媒(5) / 艺术(5)
 */

import type { PromptTemplate } from './types';

export const defaultTemplates: PromptTemplate[] = [
  // ========== 电影类 (5个) ==========
  {
    id: 'cinematic-cyberpunk-chase',
    name: '赛博朋克城市追逐',
    category: 'cinematic',
    description: '霓虹闪烁的未来都市追逐场景',
    params: {
      subject: '一名身穿黑色风衣的赛博朋克风格主角',
      action: '在雨夜的城市街道上快速奔跑，身后有追兵',
      scene: '东京风格的未来都市，高楼林立，霓虹灯闪烁，地面潮湿反光',
      camera: {
        shotType: 'medium_shot',
        movement: 'handheld',
        angle: 'eye_level',
        lens: '35mm',
      },
      style: {
        visual: 'cyberpunk',
        lighting: 'neon',
        colorGrade: 'teal orange high contrast',
        quality: '4K cinematic',
        filmStock: 'digital',
      },
      audio: 'rain, city ambience, tense music',
      aspectRatio: '16:9',
    },
    usage: 0,
  },
  {
    id: 'cinematic-epic-landscape',
    name: '史诗级自然风光',
    category: 'cinematic',
    description: '壮丽的山脉和自然景观',
    params: {
      subject: '雄伟的雪山和广阔的草原',
      action: '阳光逐渐照亮山峰，云雾在山间流动',
      scene: '喜马拉雅山脉，清晨，薄雾缭绕',
      camera: {
        shotType: 'extreme_long_shot',
        movement: 'drone',
        angle: 'birds_eye',
        lens: '24mm',
      },
      style: {
        visual: 'cinematic',
        lighting: 'golden_hour',
        colorGrade: 'warm natural colors',
        quality: '4K cinematic',
        filmStock: 'Kodak Vision3',
      },
      audio: 'wind, distant birds',
      aspectRatio: '21:9',
    },
    usage: 0,
  },
  {
    id: 'cinematic-suspense-interior',
    name: '悬疑室内场景',
    category: 'cinematic',
    description: '紧张刺激的室内悬疑氛围',
    params: {
      subject: '一个神秘的人物站在昏暗房间的窗前',
      action: '缓缓转身，面部隐藏在阴影中',
      scene: '复古风格的房间，只有一盏台灯照明，窗外雷雨交加',
      camera: {
        shotType: 'medium_shot',
        movement: 'dolly_in',
        angle: 'low_angle',
        lens: '50mm f/1.4',
      },
      style: {
        visual: 'noir',
        lighting: 'low_key',
        colorGrade: 'high contrast black white strong shadows',
        quality: '4K cinematic',
        filmStock: 'Kodak Tri-X',
      },
      audio: 'thunder, rain, clock ticking',
      aspectRatio: '16:9',
    },
    usage: 0,
  },
  {
    id: 'cinematic-sci-fi-space',
    name: '科幻太空场景',
    category: 'cinematic',
    description: '浩瀚宇宙中的科幻场景',
    params: {
      subject: '巨大的空间站悬浮在地球轨道上',
      action: '缓慢旋转，太阳能板展开，小型飞船穿梭其间',
      scene: '地球背景，星空璀璨，远处星云',
      camera: {
        shotType: 'wide_shot',
        movement: 'gimbal',
        angle: 'eye_level',
        lens: '18mm',
      },
      style: {
        visual: 'cinematic',
        lighting: 'natural',
        colorGrade: 'cool blue tech feel',
        quality: '4K cinematic',
        filmStock: 'digital',
      },
      audio: 'space ambience, radio communication',
      aspectRatio: '21:9',
    },
    usage: 0,
  },
  {
    id: 'cinematic-vintage-film',
    name: '复古电影风格',
    category: 'cinematic',
    description: '怀旧复古的电影质感',
    params: {
      subject: '一对情侣在老式火车站告别',
      action: '拥抱，挥手，火车缓缓启动',
      scene: '1940年代欧洲火车站，蒸汽火车，复古服装',
      camera: {
        shotType: 'long_shot',
        movement: 'static',
        angle: 'eye_level',
        lens: '50mm',
      },
      style: {
        visual: 'vintage',
        lighting: 'soft',
        colorGrade: 'warm yellow tint film grain',
        quality: '1080p cinematic',
        filmStock: 'Kodak Vision3 500T',
      },
      audio: 'steam train, platform announcement, piano music',
      aspectRatio: '4:3',
    },
    usage: 0,
  },

  // ========== 广告类 (5个) ==========
  {
    id: 'commercial-product-closeup',
    name: '产品特写展示',
    category: 'commercial',
    description: '高端产品广告特写',
    params: {
      subject: '一款精致的手表',
      action: '缓慢旋转展示，光线在表盘上流动',
      scene: '简洁的黑色背景，柔和的产品灯光',
      camera: {
        shotType: 'extreme_close_up',
        movement: 'gimbal',
        angle: 'eye_level',
        lens: '100mm macro',
      },
      style: {
        visual: 'commercial',
        lighting: 'studio',
        colorGrade: 'high contrast metallic texture',
        quality: '4K',
        filmStock: 'digital',
      },
      audio: 'soft music, ticking sound',
      aspectRatio: '16:9',
    },
    usage: 0,
  },
  {
    id: 'commercial-lifestyle',
    name: '生活方式场景',
    category: 'commercial',
    description: '展现美好生活状态',
    params: {
      subject: '年轻人在现代化厨房准备早餐',
      action: '煎蛋，倒咖啡，阳光透过窗户',
      scene: '北欧风格开放式厨房，晨光，绿植',
      camera: {
        shotType: 'medium_shot',
        movement: 'handheld',
        angle: 'eye_level',
        lens: '35mm',
      },
      style: {
        visual: 'commercial',
        lighting: 'natural',
        colorGrade: 'bright warm natural colors',
        quality: '4K',
        filmStock: 'digital',
      },
      audio: 'relaxed music, cooking sounds, birds',
      aspectRatio: '16:9',
    },
    usage: 0,
  },
  {
    id: 'commercial-tech-unboxing',
    name: '科技产品开箱',
    category: 'commercial',
    description: '科技产品开箱体验',
    params: {
      subject: '最新款智能手机',
      action: '从包装盒中取出，屏幕点亮，展示外观',
      scene: '简洁白色桌面，柔和的工作室灯光',
      camera: {
        shotType: 'close_up',
        movement: 'gimbal',
        angle: 'overhead',
        lens: '50mm',
      },
      style: {
        visual: 'minimalist',
        lighting: 'studio',
        colorGrade: 'clean bright tech feel',
        quality: '4K',
        filmStock: 'digital',
      },
      audio: 'unboxing sound, electronic sfx, modern music',
      aspectRatio: '16:9',
    },
    usage: 0,
  },
  {
    id: 'commercial-food',
    name: '美食广告',
    category: 'commercial',
    description: '诱人的美食展示',
    params: {
      subject: '精致的意大利面',
      action: '叉子卷起面条，蒸汽升起，酱汁滴落',
      scene: '高档餐厅环境，优雅的餐具布置',
      camera: {
        shotType: 'close_up',
        movement: 'dolly_in',
        angle: 'eye_level',
        lens: '85mm f/1.8',
      },
      style: {
        visual: 'commercial',
        lighting: 'soft',
        colorGrade: 'rich warm appetizing colors',
        quality: '4K',
        filmStock: 'digital',
      },
      audio: 'gentle music, sizzling sounds',
      aspectRatio: '16:9',
    },
    usage: 0,
  },
  {
    id: 'commercial-car-showcase',
    name: '汽车展示',
    category: 'commercial',
    description: '高端汽车动态展示',
    params: {
      subject: '豪华跑车',
      action: '在城市道路上优雅行驶，展示车身线条',
      scene: '现代化都市，夜晚灯光璀璨',
      camera: {
        shotType: 'medium_shot',
        movement: 'truck',
        angle: 'low_angle',
        lens: '35mm',
      },
      style: {
        visual: 'commercial',
        lighting: 'neon',
        colorGrade: 'sleek premium colors',
        quality: '4K',
        filmStock: 'digital',
      },
      audio: 'engine sound, city ambience, electronic music',
      aspectRatio: '16:9',
    },
    usage: 0,
  },

  // ========== 社媒类 (5个) ==========
  {
    id: 'social-viral-opening',
    name: 'Viral短视频开场',
    category: 'social',
    description: '吸引人的短视频开场',
    params: {
      subject: '创作者面对镜头',
      action: '充满活力的开场手势，眼神接触',
      scene: '色彩丰富的背景，良好的照明',
      camera: {
        shotType: 'medium_shot',
        movement: 'handheld',
        angle: 'eye_level',
        lens: '24mm',
      },
      style: {
        visual: 'cinematic',
        lighting: 'high_key',
        colorGrade: 'vibrant energetic colors',
        quality: '1080p',
        filmStock: 'digital',
      },
      audio: 'upbeat music',
      aspectRatio: '9:16',
    },
    usage: 0,
  },
  {
    id: 'social-tutorial',
    name: '教程讲解视频',
    category: 'social',
    description: '知识分享类内容',
    params: {
      subject: '讲师在白板前讲解',
      action: '手势辅助讲解，指向图表',
      scene: '简洁明亮的教室或工作室',
      camera: {
        shotType: 'medium_shot',
        movement: 'static',
        angle: 'eye_level',
        lens: '35mm',
      },
      style: {
        visual: 'documentary',
        lighting: 'soft',
        colorGrade: 'clean natural colors',
        quality: '1080p',
        filmStock: 'digital',
      },
      audio: 'clear voice, background music',
      aspectRatio: '16:9',
    },
    usage: 0,
  },
  {
    id: 'social-travel-vlog',
    name: '旅行Vlog片段',
    category: 'social',
    description: '精彩的旅行瞬间',
    params: {
      subject: '旅行者在著名景点',
      action: '张开双臂，享受风景，转身微笑',
      scene: '标志性景点背景，阳光明媚',
      camera: {
        shotType: 'long_shot',
        movement: 'gimbal',
        angle: 'eye_level',
        lens: '24mm',
      },
      style: {
        visual: 'cinematic',
        lighting: 'golden_hour',
        colorGrade: 'warm travel vibes',
        quality: '4K',
        filmStock: 'digital',
      },
      audio: 'travel music, ambient sounds',
      aspectRatio: '9:16',
    },
    usage: 0,
  },
  {
    id: 'social-cute-pet',
    name: '萌宠视频',
    category: 'social',
    description: '可爱的宠物瞬间',
    params: {
      subject: '可爱的猫咪或小狗',
      action: ' playful动作，歪头，眨眼',
      scene: '温馨的家庭环境，柔和的自然光',
      camera: {
        shotType: 'close_up',
        movement: 'static',
        angle: 'eye_level',
        lens: '50mm',
      },
      style: {
        visual: 'cinematic',
        lighting: 'natural',
        colorGrade: 'warm cozy tones',
        quality: '1080p',
        filmStock: 'digital',
      },
      audio: 'cute sounds, gentle music',
      aspectRatio: '9:16',
    },
    usage: 0,
  },
  {
    id: 'social-transition',
    name: '变装转场效果',
    category: 'social',
    description: '流行的转场视频',
    params: {
      subject: '创作者做出特定动作',
      action: '遮挡镜头或旋转，完成造型转换',
      scene: '两个不同风格的场景',
      camera: {
        shotType: 'medium_shot',
        movement: 'handheld',
        angle: 'eye_level',
        lens: '24mm',
      },
      style: {
        visual: 'music_video',
        lighting: 'dramatic',
        colorGrade: 'bold contrast transformation',
        quality: '1080p',
        filmStock: 'digital',
      },
      audio: 'trending music, transition sfx',
      aspectRatio: '9:16',
    },
    usage: 0,
  },

  // ========== 艺术类 (5个) ==========
  {
    id: 'artistic-abstract',
    name: '抽象艺术动画',
    category: 'artistic',
    description: '流动的抽象视觉效果',
    params: {
      subject: '流动的色彩和形状',
      action: '缓慢变形，色彩融合，有机运动',
      scene: '纯黑背景，粒子效果',
      camera: {
        shotType: 'close_up',
        movement: 'static',
        angle: 'eye_level',
        lens: '50mm',
      },
      style: {
        visual: 'cinematic',
        lighting: 'dramatic',
        colorGrade: 'vibrant fluid colors',
        quality: '4K',
        filmStock: 'digital',
      },
      audio: 'ambient electronic music',
      aspectRatio: '16:9',
    },
    usage: 0,
  },
  {
    id: 'artistic-ink-wash',
    name: '水墨画风格',
    category: 'artistic',
    description: '中国传统水墨意境',
    params: {
      subject: '山水风景，松树，云雾',
      action: '水墨晕染，笔触流动',
      scene: '留白意境，传统中国画风格',
      camera: {
        shotType: 'long_shot',
        movement: 'pan',
        angle: 'high_angle',
        lens: '35mm',
      },
      style: {
        visual: 'cinematic',
        lighting: 'soft',
        colorGrade: 'monochrome ink tones',
        quality: '4K',
        filmStock: 'digital',
      },
      audio: 'traditional chinese music, water sounds',
      aspectRatio: '16:9',
    },
    usage: 0,
  },
  {
    id: 'artistic-surreal',
    name: '超现实主义',
    category: 'artistic',
    description: '梦境般的超现实场景',
    params: {
      subject: '不可能存在的场景组合',
      action: '违反物理定律的运动，变形',
      scene: '梦幻般的抽象空间',
      camera: {
        shotType: 'wide_shot',
        movement: 'gimbal',
        angle: 'dutch_angle',
        lens: '18mm',
      },
      style: {
        visual: 'cinematic',
        lighting: 'dramatic',
        colorGrade: 'surreal dreamy colors',
        quality: '4K',
        filmStock: 'digital',
      },
      audio: 'surreal ambient soundscape',
      aspectRatio: '16:9',
    },
    usage: 0,
  },
  {
    id: 'artistic-stop-motion',
    name: '定格动画风格',
    category: 'artistic',
    description: '手工感的定格动画',
    params: {
      subject: '粘土或木偶角色',
      action: '逐帧动画，跳跃和变形',
      scene: '手工制作的微缩场景',
      camera: {
        shotType: 'medium_shot',
        movement: 'static',
        angle: 'eye_level',
        lens: '50mm',
      },
      style: {
        visual: 'cinematic',
        lighting: 'soft',
        colorGrade: 'warm handmade feel',
        quality: '1080p',
        filmStock: 'digital',
      },
      audio: 'whimsical music, stop motion sfx',
      aspectRatio: '16:9',
    },
    usage: 0,
  },
  {
    id: 'artistic-hand-drawn',
    name: '手绘动画效果',
    category: 'artistic',
    description: '手绘风格的动画',
    params: {
      subject: '线条勾勒的角色或物体',
      action: '线条绘制过程，颜色填充',
      scene: '白纸背景，彩色线条',
      camera: {
        shotType: 'close_up',
        movement: 'static',
        angle: 'overhead',
        lens: '50mm',
      },
      style: {
        visual: 'anime',
        lighting: 'natural',
        colorGrade: 'colorful hand drawn style',
        quality: '1080p',
        filmStock: 'digital',
      },
      audio: 'creative music, drawing sounds',
      aspectRatio: '16:9',
    },
    usage: 0,
  },
];

// 按分类获取模板
export function getTemplatesByCategory(category: PromptTemplate['category']): PromptTemplate[] {
  return defaultTemplates.filter(t => t.category === category);
}

// 获取所有模板
export function getAllTemplates(): PromptTemplate[] {
  return defaultTemplates;
}

// 根据ID获取模板
export function getTemplateById(id: string): PromptTemplate | undefined {
  return defaultTemplates.find(t => t.id === id);
}
